"""post title改为160的长度

Revision ID: a2f6ff925891
Revises: 
Create Date: 2020-04-29 09:13:35.813144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2f6ff925891'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=60),
               type_=sa.String(length=160),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.String(length=160),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=60),
               existing_nullable=True)
    # ### end Alembic commands ###
